version: '3'
services:
  db:
    image: postgres:9.6.5-alpine
    restart: always
    ports: ["5432:5432"]
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-docker}
  api:
    build: ./api
    depends_on:
      - db
    ports: ["3001:3001"]
    volumes:
      - ./api:/app:delegated
  client:
    build: ./client
    depends_on:
      - api
    ports: ["3000:3000"]
    volumes:
      - ./client:/app:delegated
